// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UuidService.proto

package com.weswu.clouduuid.grpc;

public interface CommonRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.weswu.clouduuid.grpc.CommonResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string content = 1;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
