// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UuidService.proto

package com.weswu.clouduuid.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.weswu.clouduuid.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
