// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UuidService.proto

package com.weswu.clouduuid.grpc;

public interface SequentialIdReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.weswu.clouduuid.grpc.SequentialIdReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string domain = 1;</code>
   */
  java.lang.String getDomain();
  /**
   * <code>optional string domain = 1;</code>
   */
  com.google.protobuf.ByteString
      getDomainBytes();

  /**
   * <code>optional string tag = 2;</code>
   */
  java.lang.String getTag();
  /**
   * <code>optional string tag = 2;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
