// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UuidService.proto

package com.weswu.clouduuid.grpc;

public final class UuidService {
  private UuidService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weswu_clouduuid_grpc_SequentialIdReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_weswu_clouduuid_grpc_SequentialIdReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weswu_clouduuid_grpc_CreateSequentialIdSpaceReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_weswu_clouduuid_grpc_CreateSequentialIdSpaceReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weswu_clouduuid_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_weswu_clouduuid_grpc_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weswu_clouduuid_grpc_UuidResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_weswu_clouduuid_grpc_UuidResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weswu_clouduuid_grpc_CommonResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_weswu_clouduuid_grpc_CommonResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UuidService.proto\022\030com.weswu.clouduuid" +
      ".grpc\".\n\017SequentialIdReq\022\016\n\006domain\030\001 \001(\t" +
      "\022\013\n\003tag\030\002 \001(\t\"N\n\032CreateSequentialIdSpace" +
      "Req\022\016\n\006domain\030\001 \001(\t\022\013\n\003tag\030\002 \001(\t\022\023\n\013desc" +
      "ription\030\003 \001(\t\"\007\n\005Empty\"\030\n\010UuidResp\022\014\n\004uu" +
      "id\030\001 \001(\003\"\035\n\nCommonResp\022\017\n\007content\030\001 \001(\t*" +
      ")\n\010UuidType\022\016\n\nSEQUENTIAL\020\000\022\r\n\tSNOWFLAKE" +
      "\020\0012\363\004\n\016UuidController\022x\n\030createSequentia" +
      "llIdSpace\0224.com.weswu.clouduuid.grpc.Cre" +
      "ateSequentialIdSpaceReq\032$.com.weswu.clou",
      "duuid.grpc.CommonResp\"\000\022m\n\030deleteSequent" +
      "iallIdSpace\022).com.weswu.clouduuid.grpc.S" +
      "equentialIdReq\032$.com.weswu.clouduuid.grp" +
      "c.CommonResp\"\000\022\\\n\021deleteAllIdSpaces\022\037.co" +
      "m.weswu.clouduuid.grpc.Empty\032$.com.weswu" +
      ".clouduuid.grpc.CommonResp\"\000\022b\n\017getSeque" +
      "ntialId\022).com.weswu.clouduuid.grpc.Seque" +
      "ntialIdReq\032\".com.weswu.clouduuid.grpc.Uu" +
      "idResp\"\000\022W\n\016getSnowFlakeId\022\037.com.weswu.c" +
      "louduuid.grpc.Empty\032\".com.weswu.clouduui",
      "d.grpc.UuidResp\"\000\022]\n\024getCachedSnowFlakeI" +
      "d\022\037.com.weswu.clouduuid.grpc.Empty\032\".com" +
      ".weswu.clouduuid.grpc.UuidResp\"\000B\002P\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_weswu_clouduuid_grpc_SequentialIdReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weswu_clouduuid_grpc_SequentialIdReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_weswu_clouduuid_grpc_SequentialIdReq_descriptor,
        new java.lang.String[] { "Domain", "Tag", });
    internal_static_com_weswu_clouduuid_grpc_CreateSequentialIdSpaceReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_weswu_clouduuid_grpc_CreateSequentialIdSpaceReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_weswu_clouduuid_grpc_CreateSequentialIdSpaceReq_descriptor,
        new java.lang.String[] { "Domain", "Tag", "Description", });
    internal_static_com_weswu_clouduuid_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_weswu_clouduuid_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_weswu_clouduuid_grpc_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_com_weswu_clouduuid_grpc_UuidResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_weswu_clouduuid_grpc_UuidResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_weswu_clouduuid_grpc_UuidResp_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_com_weswu_clouduuid_grpc_CommonResp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_weswu_clouduuid_grpc_CommonResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_weswu_clouduuid_grpc_CommonResp_descriptor,
        new java.lang.String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
