// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UuidService.proto

package com.weswu.clouduuid.grpc;

/**
 * Protobuf type {@code com.weswu.clouduuid.grpc.UuidResp}
 */
public  final class UuidResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.weswu.clouduuid.grpc.UuidResp)
    UuidRespOrBuilder {
  // Use UuidResp.newBuilder() to construct.
  private UuidResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UuidResp() {
    uuid_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UuidResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            uuid_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.weswu.clouduuid.grpc.UuidService.internal_static_com_weswu_clouduuid_grpc_UuidResp_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.weswu.clouduuid.grpc.UuidService.internal_static_com_weswu_clouduuid_grpc_UuidResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.weswu.clouduuid.grpc.UuidResp.class, com.weswu.clouduuid.grpc.UuidResp.Builder.class);
  }

  public static final int UUID_FIELD_NUMBER = 1;
  private long uuid_;
  /**
   * <code>optional int64 uuid = 1;</code>
   */
  public long getUuid() {
    return uuid_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uuid_ != 0L) {
      output.writeInt64(1, uuid_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uuid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uuid_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.weswu.clouduuid.grpc.UuidResp)) {
      return super.equals(obj);
    }
    com.weswu.clouduuid.grpc.UuidResp other = (com.weswu.clouduuid.grpc.UuidResp) obj;

    boolean result = true;
    result = result && (getUuid()
        == other.getUuid());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUuid());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.weswu.clouduuid.grpc.UuidResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weswu.clouduuid.grpc.UuidResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weswu.clouduuid.grpc.UuidResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weswu.clouduuid.grpc.UuidResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weswu.clouduuid.grpc.UuidResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.weswu.clouduuid.grpc.UuidResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.weswu.clouduuid.grpc.UuidResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.weswu.clouduuid.grpc.UuidResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.weswu.clouduuid.grpc.UuidResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.weswu.clouduuid.grpc.UuidResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.weswu.clouduuid.grpc.UuidResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.weswu.clouduuid.grpc.UuidResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.weswu.clouduuid.grpc.UuidResp)
      com.weswu.clouduuid.grpc.UuidRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weswu.clouduuid.grpc.UuidService.internal_static_com_weswu_clouduuid_grpc_UuidResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weswu.clouduuid.grpc.UuidService.internal_static_com_weswu_clouduuid_grpc_UuidResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.weswu.clouduuid.grpc.UuidResp.class, com.weswu.clouduuid.grpc.UuidResp.Builder.class);
    }

    // Construct using com.weswu.clouduuid.grpc.UuidResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      uuid_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.weswu.clouduuid.grpc.UuidService.internal_static_com_weswu_clouduuid_grpc_UuidResp_descriptor;
    }

    public com.weswu.clouduuid.grpc.UuidResp getDefaultInstanceForType() {
      return com.weswu.clouduuid.grpc.UuidResp.getDefaultInstance();
    }

    public com.weswu.clouduuid.grpc.UuidResp build() {
      com.weswu.clouduuid.grpc.UuidResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.weswu.clouduuid.grpc.UuidResp buildPartial() {
      com.weswu.clouduuid.grpc.UuidResp result = new com.weswu.clouduuid.grpc.UuidResp(this);
      result.uuid_ = uuid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.weswu.clouduuid.grpc.UuidResp) {
        return mergeFrom((com.weswu.clouduuid.grpc.UuidResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.weswu.clouduuid.grpc.UuidResp other) {
      if (other == com.weswu.clouduuid.grpc.UuidResp.getDefaultInstance()) return this;
      if (other.getUuid() != 0L) {
        setUuid(other.getUuid());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.weswu.clouduuid.grpc.UuidResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.weswu.clouduuid.grpc.UuidResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long uuid_ ;
    /**
     * <code>optional int64 uuid = 1;</code>
     */
    public long getUuid() {
      return uuid_;
    }
    /**
     * <code>optional int64 uuid = 1;</code>
     */
    public Builder setUuid(long value) {
      
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 uuid = 1;</code>
     */
    public Builder clearUuid() {
      
      uuid_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.weswu.clouduuid.grpc.UuidResp)
  }

  // @@protoc_insertion_point(class_scope:com.weswu.clouduuid.grpc.UuidResp)
  private static final com.weswu.clouduuid.grpc.UuidResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.weswu.clouduuid.grpc.UuidResp();
  }

  public static com.weswu.clouduuid.grpc.UuidResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UuidResp>
      PARSER = new com.google.protobuf.AbstractParser<UuidResp>() {
    public UuidResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UuidResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UuidResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UuidResp> getParserForType() {
    return PARSER;
  }

  public com.weswu.clouduuid.grpc.UuidResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

