// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UuidService.proto

package com.weswu.clouduuid.grpc;

public interface UuidRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.weswu.clouduuid.grpc.UuidResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 uuid = 1;</code>
   */
  long getUuid();
}
