// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UuidService.proto

package com.weswu.clouduuid.grpc;

/**
 * Protobuf enum {@code com.weswu.clouduuid.grpc.UuidType}
 */
public enum UuidType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SEQUENTIAL = 0;</code>
   */
  SEQUENTIAL(0),
  /**
   * <code>SNOWFLAKE = 1;</code>
   */
  SNOWFLAKE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SEQUENTIAL = 0;</code>
   */
  public static final int SEQUENTIAL_VALUE = 0;
  /**
   * <code>SNOWFLAKE = 1;</code>
   */
  public static final int SNOWFLAKE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static UuidType valueOf(int value) {
    return forNumber(value);
  }

  public static UuidType forNumber(int value) {
    switch (value) {
      case 0: return SEQUENTIAL;
      case 1: return SNOWFLAKE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<UuidType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      UuidType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<UuidType>() {
          public UuidType findValueByNumber(int number) {
            return UuidType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.weswu.clouduuid.grpc.UuidService.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final UuidType[] VALUES = values();

  public static UuidType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private UuidType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.weswu.clouduuid.grpc.UuidType)
}

